#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ `uname` = 'Darwin' ]]; then
  mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3
  ln -fs $DIR/subl3/Packages ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
elif [[ `uname` = 'Linux' ]]; then
  mkdir -p ~/.config/sublime-text-3
  ln -fs $DIR/subl3/Packages ~/.config/sublime-text-3/Packages
fi